### ISSUE TITLE
Problem with add new variable in saeSim 

### ISSUE THREAD

**Issue by easbi** [wahani/saeSim#40]
actually, i want to add replicate data in one saesim using this code below: 

```r
sizeN <- c(50,250,50,100,200,150,50,150,100,150,100,50) #size of population in each domain
m = 12  #domain
x_true <- c(193.08 , 189.14, 186.75, 204.72, 184.63, 187.94, 201.13, 198.91, 183.60, 185.36, 205.76, 196.11) # True Xi for each domain
```

```r
#generate process using saeSim 
set.seed(123)
setup <- base_id(nDomains = m, nUnits = sizeN) %>%
  sim_gen(gen_generic(runif, min = 180, max = 210, name = "xi", groupVars = "idD")) %>% 
  sim_gen(gen_generic(rep(x_true, sizeN), name = "Xi_true", groupVars = "idD")) %>%   
  as.data.frame()
```

but the error message is 

```
> Error in do.call(generator, c(length(nrowGroup), genArgs)) : 
  'what' must be a function or character string
```

is there any solution without using gen_genric function ?  thanks before :)

**Comment by wahani** [comment]
Hi. Thank you for your question.

I think a flexibel way of doing what you want, is to put all your constant (constant accross simulations) population values next to the generation of the IDs. `base_id` is just producing a `data.frame` and as such we can simply replace it by something like:

```r
library(saeSim)
nUnits <- sizeN <- c(50,250,50,100,200,150,50,150,100,150,100,50) #size of population in each domain
nDomains <- m <- 12  #domain

my_pop <- function(nDomains, nUnits) {
  my_x = c(
    193.08 , 189.14, 186.75, 204.72, 184.63, 187.94, 201.13, 198.91, 183.60, 185.36, 
    205.76, 196.11)
  pop <- base_id(nDomains, nUnits)
  pop$Xi_true <- rep(my_x, times = nUnits)
  pop
}

set.seed(123)
my_pop(nDomains = m, nUnits = sizeN) %>%
  sim_gen(gen_generic(runif, min = 180, max = 210, name = "xi", groupVars = "idD"))
```

Feel free to comment if I got it all wrong.

**Comment by easbi** [comment]
thank you, I think this is a great solution. actually I just found this package can be flexible in data simulation especially on SAE.

**Comment by wahani** [comment]
Glad to hear it. I used this package as part of my own research, maybe it is interesting to see a complete study: https://github.com/wahani/dissertation/blob/master/R/simFromUnitToAreaLevel.R
